### PR TITLE
Fix `best_output_block_updated` erroneously remaining at `false`

### LINKED ISSUE #1941: Panic error `called 'Option::unwrap()' on a 'None' value`
```console
Smoldot has panicked while executing task `tx-service-asset-hub-polkadot`. This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at /__w/smoldot/smoldot/lib/src/transactions/light_pool.rs:829:59:
called `Option::unwrap()` on a `None` value
a @ index-DjGwj_3O.js:165
n.onmessage @ index-DjGwj_3O.js:165
```

I randomly got this today, hasn't yet been able to identify a reproduction step.

### LINKED ISSUE #2023: Smoldot has panicked while executing task `tx-service-asset-hub-westend`
```
panicked at /__w/smoldot/smoldot/lib/src/transactions/light_pool.rs:829:59:
called `Option::unwrap()` on a `None` value
```

[The level 6 logs](https://github.com/user-attachments/files/17651812/smoldot-logs.log).

This is happening non-stop on parachains on the development tools that we are about to deliver 😞.

### PR DESCRIPTION
**Pull request by tomaka**
Fix #2023 
Fix #1941

Work time: 20mn

### CODE REVIEW

File: lib/src/chain/async_tree.rs [hunk 1]
```diff
@@ -915,6 +915,13 @@ where
                 let mut pruned_finalized = None;
                 let mut best_output_block_updated = false;
 
+                // Since we change the finalized block, if the output best block is equal to this
+                // finalized block, that means it is modified, even though its value might remain
+                // at `None`.
+                if self.output_best_block_index.is_none() {
+                    best_output_block_updated = true;
+                }
```
Comment (tomaka) [inline lib/src/chain/async_tree.rs:923]: That's the bugfix. The rest of the changes are one typo, and clarifications.
