### PR TITLE
Fix panic in `async_tree.rs`

### LINKED ISSUE #1712: panicked at /__w/smoldot/smoldot/light-base/src/runtime_service.rs:1845:35
```
[smoldot] Smoldot v2.0.22. Current memory usage: 64.5 MiB. Average download: 99.8 kiB/s. Average upload: 3.1 kiB/s. Average CPU cores: 0.17.
0132e122:0x18b7b0 Smoldot has panicked while executing task runtime-asset-hub-kusama. This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at /__w/smoldot/smoldot/light-base/src/runtime_[service.rs:1845](http://service.rs:1845/):35:
called Option::unwrap() on a None value
```

## Steps to Reproduce

1. Have substrate connect installed and open the options page then open the chrome console
2. Go to https://paritytech.github.io/substrate-connect/demo/
3. Connect and disconnect to VPN or turn your internet on and off
4. Refresh the webpage in step 2.
5. Check the logs in the substrate connect options console and also the logs in the webpage

### PR DESCRIPTION
**Pull request by tomaka**
Fix #1712 

Work time: 1h

### CODE REVIEW

File: lib/src/chain/async_tree.rs [hunk 1]
```diff
@@ -811,7 +811,10 @@ where
         assert!(match (self.input_finalized_index, new_best_block) {
             (Some(f), Some(b)) => self.non_finalized_blocks.is_ancestor(f, b),
             (Some(_), None) => false,
-            (None, Some(_)) => true,
+            (None, Some(b)) => {
+                assert!(self.non_finalized_blocks.contains(b));
```
Comment (tomaka) [inline lib/src/chain/async_tree.rs:815]: This newly-added asset is not strictly related to the bug, but it might catch similar problems earlier on.
